name: CI
on: [push, pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Node.js (v${{ matrix.node-version }}.x)
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: check Node.js version
        run: node --version

      - name: install npm dependencies
        run: npm install

      - name: run tests
        run: npm run test
